### ISSUE TITLE
Use computed properties instead of methods

### ISSUE THREAD

**Issue by cpoenisch** [awsler/vue-frontend#1]
See differences between computed/watched properties vs. methods ([Vue doc](https://vuejs.org/v2/guide/computed.html#Computed-vs-Watched-Property))

https://github.com/awsler/vue-frontend/blob/bc6d0eebe2801bbe92504e34a442354aab7aeea6/src/components/EventListItem.vue#L43-L64

**Comment by ttmapr** [comment]
Done.
I added computed properties to be used in the HTML part of EventListItem.vue (However, those computed properties still use the methods).

**Comment by cpoenisch** [comment]
Fixed by commit 2f45e3581aad0c2cd6c1c72894bc8ae8c3cd7095. Next time directly use a [closing/fixed keyword](https://help.github.com/articles/closing-issues-using-keywords/) in your commit message. :sparkles:
